#! /bin/sh
# Replace your own directory
output='/home/ali/Pictures/Screenshots/%Y-%m-%d-%T-screenshot.png'

case "$1" in
	"select") scrot "$output" --select --line mode=edge || exit ;;
	"window") scrot "$output" --focused --border || exit ;;
	*) scrot "$output" || exit ;;
esac
