require "options"
require "keymap-config"
-- require "packer-config"
-- require "colorschemes-config.dracula"
-- require "nvim-tree-config"
-- require "lsp-config.language-servers"
-- require "lsp-config.nvim-cmp"
-- require "lualine-config"
-- require "barbar-config"
-- require "treesitter-config"
